[package]
name = "prompt-rust"
version = "0.1.1"
edition = "2021"
description = "a high-level io function similar to Python's input function."
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
